### PR TITLE
Remove unused EncoderTestEntry and PrecisionDockingStatus

### PR DESCRIPTION
**Pull request by brean**
rosnodejs will not start because it will not try to generate js-files for them but relies on their import.

### CODE REVIEW

**Comment by mintar** [comment]
I'd prefer to keep these messages, because the current state of the package corresponds to the `mirMsgs` package on the real MiR software, and perhaps we'll need them later on. For example, SoundEvent is actually published by the MiR, just commented out at the moment.

The fact that these messages are not being built is a bug. I'm proposing a fix in #98, and I'd prefer to merge #98 instead of this PR. What do you think?

**Comment by brean** [comment]
Works for me, I just delete the files after checkout in my Dockerfile.
Might also be worth a bug-report to rosnodejs to ignore files that are not in the CMakelist.txt

**Comment by mintar** [comment]
> Works for me, I just delete the files after checkout in my Dockerfile.

Ok, I've merged #98. Now deleting the files shouldn't be necessary any more, right?

> Might also be worth a bug-report to rosnodejs to ignore files that are not in the CMakelist.txt

Yes, that sounds like a good idea. It was a bug in mir_msgs, but probably also a bug in rosnodejs.

**Comment by brean** [comment]
yes, it is working now without my workaround (deleting files).

**Pull request closed without merging**
